### ISSUE TITLE
XLS Export

### ISSUE THREAD

**Issue by HenryMiller** [richardschoen/ibmijasper#3]
Hello,
I cannot export sample report in EXCEL.
Which Apache POI version is required.
I'm currently running poi-3.8-20120326.jar.

Exception in thread "main" java.lang.NoSuchMethodError: org/apache/poi/hssf/util/HSSFColor.getTripletHash()Ljava/util/Map;
 at net.sf.jasperreports.engine.export.JRXlsExporter.<clinit>(JRXlsExporter.java:160)                                     
 at com.valadd.report.engine.Generator.printReport(Generator.java:425)                                                    
 at com.valadd.report.engine.Generator.iPrintReport(Generator.java:356)                                                   
 at com.valadd.report.engine.GenReport.runTest(GenReport.java:71)                                                         
 at com.valadd.report.engine.GenReport.main(GenReport.java:37)

**Comment by richardschoen** [comment]
It would appear the POI component is in the rrejars.jar file. Pete Helgren must have packaged them here when he built the code. Version looks like: **poi-3.7-20101029.jar**

**Comment by HenryMiller** [comment]
Hi Richards,
I had a POI Jar file in /qibm/userdata/java400/ext folder and RREGEN was using that one.
I deleted it and now it works fine.
Thank you for your help.

**Comment by richardschoen** [comment]
Glad that worked for you.
